title: Scratch Site
email: alexjpkim AT gmail
description: Alex Kim's thoughts and projects related to cognition, computation, and consciousness.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ajpkim
github_username:  ajpkim

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Jekyll Collections
collections:
  projects:
    output: true # Set to render files in _projects folder
    permalink: /:collection/:title/
  pages:
    output: true
    permalink: /:title/
  thoughts:
    output: true
    permalink: /:collection/:title/

# Navigation bar
navPages:
  - title: projects
    url: /projects
  - title: thoughts
    url: /thoughts
  - title: about
    url: /about
  