#+BEGIN_EXPORT html
---
layout: default
title: an org convert
---
#+END_EXPORT

* Making Sense of Sense-Making
:PROPERTIES:
:CUSTOM_ID:       f06991dc-cc77-4b1b-b7bb-403159a60d23
:END:

September, 2020

---

How intelligent systems learn rich representations that exploit
structure in the world to solve adaptive challenges is the major
question of intelligence. How and why does intelligence emerge in
complex adaptive systems? How can we build systems endowed with similar
representational infrastructure for understanding the world and acting
well in it?

Here I begin building an intuitive perspective for understanding how
adaptive systems gain meaningful knowledge of the world which supports
intelligent behavior. My interest is in the emergence of meaning that
leads to intelligent behaviors for adaptive systems, in contrast to a
survey of the specific cognitive mechanisms supporting human
intelligence. I want to develop some tools for thinking about the
evolutionary learning process that developed such complex systems as the
human mind. Below I aim to motivate the importance of the subjective and
action-oriented nature of natural intelligence for understanding the
search and learning process (evolution) that produced general
intelligence on Earth.

---

* TOC                                                                   :TOC:
- [[Making Sense of Sense-Making][Making Sense of Sense-Making]]
- [[1. Adaptive systems are subjective and action-oriented][1. Adaptive systems are subjective and action-oriented]]
    - [[1.1. intelligence is about exploiting emergent structure][1.1. intelligence is about exploiting emergent structure]]
    - [[1.2. roadmap][1.2. roadmap]]
- [[2. The appearance of a world][2. The appearance of a world]]
    - [[2.1. cognitive architecture defines subjective frame][2.1. cognitive architecture defines subjective frame]]
    - [[2.2. phenomenal contingencies][2.2. phenomenal contingencies]]
    - [[2.3. meaning emerges within subjective world structure][2.3. meaning emerges within subjective world structure]]
- [[3. Umwelt][3. Umwelt]]
    - [[3.1. the subjective perspective of living systems is crucial][3.1. the subjective perspective of living systems is crucial]]
    - [[3.3. subjective and action-oriented sense-making][3.3. subjective and action-oriented sense-making]]
- [[4. Exploiting structure][4. Exploiting structure]]
    - [[4.1. using world knowledge to do work][4.1. using world knowledge to do work]]
    - [[4.2. biology exploits physics and creates complexity][4.2. biology exploits physics and creates complexity]]
    - [[4.3. adaptive transitions in information processing][4.3. adaptive transitions in information processing]]
    - [[4.4. adaptations exploit accessible structure][4.4. adaptations exploit accessible structure]]
- [[5. Affordances][5. Affordances]]
    - [[5.1. perceiving possibilities][5.1. perceiving possibilities]]
    - [[5.2. expanding the concept of affordances][5.2. expanding the concept of affordances]]
    - [[5.3. exploring evolutionary affordances][5.3. exploring evolutionary affordances]]
    - [[5.4. situated action-oriented agents][5.4. situated action-oriented agents]]
- [[6. Adaptive world models][6. Adaptive world models]]
    - [[6.1. converging adaptive representational concepts][6.1. converging adaptive representational concepts]]
    - [[6.2. life without objects?][6.2. life without objects?]]
    - [[6.3. representational scaffolding][6.3. representational scaffolding]]
- [[7. Wrapping up][7. Wrapping up]]

** 1. Adaptive systems are subjective and action-oriented
   :PROPERTIES:
   :ID:       d2dde72d-166b-4a3e-b89c-f064d9c1bd66
   :CUSTOM_ID: 7df31510-0f49-4af6-b1d9-eac9dc11d5f9
   :END:
Thinking about how and why intelligence emerges forces us to be in touch
with the sole existence proof of general intelligence provided to us by
nature. This proof reveals to us that natural intelligence is about
processing information about the world to guide adaptive behavior. This
simple framing has important consequences. Studying natural intelligence
puts subjectivity and action-in-the-world center stage and demands we
try and piece together the conditions within which new forms of
sense-making emerge. Living systems have a point of view on the world,
and evolution learned to represent such phenomena as chemical gradients,
intuitive physics, and social dynamics for the purpose of producing
adaptive behavior to support this point of view. How?

*** 1.1. intelligence is about exploiting emergent structure
    :PROPERTIES:
    :ID:       0e6514fa-be10-4c21-87d9-0fdd6fdde82b
    :CUSTOM_ID: 70e4f2de-b2c8-4eaa-86f0-6b931f4475af
    :END:
In the big picture what I'm interested in is a story which describes the
evolution of intelligence through transitions in information processing
and cycles of creating and exploiting emergent structure in the world;
the richer and more abstract the information about the world a cognitive
system is able to exploit, the wider its ability to impact the world and
solve complex problems. I perceive this project of describing the
relationship between living systems and emergent structure as filling in
the space between physics and phenomenology. The story of intelligence.
This is a grandiose picture, but my weakness for philosophy and big
picture conceptual framings mandates I define the project as such.

*** 1.2. roadmap
    :PROPERTIES:
    :ID:       2a7641d4-22d5-4ff5-acb3-c16bb7a68167
    :CUSTOM_ID: 70171a53-1287-4799-a889-6f1fda70caa9
    :END:
Below I begin contextualizing how natural intelligence is fundamentally
situated in the world and the product of subjective sense-making
evolution developed in service of guiding adaptive behavior. In the
first section I begin to frame the problem of intelligence from the
subjective perspective and illuminate how cognitive systems are
subjective world models. In the second section I introduce Jakob von
Uexküll's Umwelt theory to further illustrate the subjective perspective
of living systems. In the third section I explicate what it means for
cognitive systems to "exploit structure in the world". In the fourth
section I introduce James Gibson's theory of affordances as a
theoretical concept to help conceptualize subjectively perceived
structure and the reciprocity defining the relationship between
cognitive systems and the world. In the fifth section I discuss the
representational scaffolding and flexibility underlying human
intelligence. At the end I will briefly review the discussion and
restate the subjective nature of the world models built by evolution and
their adaptive purpose.

** 2. The appearance of a world
   :PROPERTIES:
   :ID:       eb9600e7-b9bd-49a3-8335-01aa07e164c2
   :CUSTOM_ID: c0179262-aec1-4752-9d15-b06cf0b91110
   :END:
Cognitive systems each possess a particular perspective on the world
which is defined by the network of information processing governing its
interaction with the world. For all of us there is a subjective world
that appears at each moment of our existence. Our brains and bodies
continually conspire with the environment in building the world that
appears to us. This cognitive handiwork simply is the world for us,
reflecting all the information about the world that has meaning to us.
The colors I see, the sounds I hear, the emotions I feel, my entire
psychological sense of self - everything - manifests from the
interaction between my cognitive architecture and the outside world.
Take away one of my cone types and my world is different. Take away my
ability to perceive the mental states of others and my world is
different. Give me language when I have none and my world is different.

*** 2.1. cognitive architecture defines subjective frame
    :PROPERTIES:
    :ID:       36bcf7df-5c25-4d99-a94b-d3ef659430a2
    :CUSTOM_ID: 3682a5e0-ba81-4e5b-b19b-4f9b986d0825
    :END:
The subjective world is an amalgamation of features of the outside world
that have been captured and integrated into a perspective on the world,
the output of a world model engaged in a dance of interpretation and
action with the external world. The point here is that the world in
experience - from a cognitive system's perspective - is defined by the
particular means the system possesses for capturing and processing
information about the world. What we know about the world and how we act
flows from our sense-making capabilities and the structure we can
perceive in the world.

*** 2.2. phenomenal contingencies
    :PROPERTIES:
    :ID:       42166ffb-e6f8-49ab-a3c3-1d8ad21c39f6
    :CUSTOM_ID: ee07b1d1-116b-4065-b7a6-e16ce735e7c0
    :END:
I want to emphasize that despite it being trivially true that our
subjective frame follows from our physical organization, it is difficult
to really internalize the contingent character of the familiar
phenomenological tropes that format our own subjective worlds. Such
internalization helps us see the world from different perspectives and
appreciate the power and purpose of different representational features
and environmental engagements. Our subjective worlds could be different,
and are very different from organisms like apes, fish, and ants. The
single physical world we all exist within supports countless world
models; humans collectively occupy only a small area in the space of all
possible minds. However, even within this narrow band there is a wide
space of possibilities. One can read the amazing and sometimes tragic
literature of abnormal psychology to gain a deeper appreciation for the
ways in which our subjective realities could be different given
adjustments to our cognitive architectures.

*** 2.3. meaning emerges within subjective world structure
    :PROPERTIES:
    :ID:       9df22323-4ab0-4717-ab19-6189395c53f9
    :CUSTOM_ID: c7128fe1-3ea9-4efc-8593-1c8cdb2556c0
    :END:
So why focus on the subjective perspective of cognitive systems at all?
Because it is the structure of a cognitive systems subjective world
which entirely reflects its knowledge of the outside world, ability to
integrate new information, and horizon of possible actions. Subjective
meaning is the fuel for intelligence as a system can only act in
response to signals that have meaning for it. If we want to understand
how adaptive systems learn to make sense of the world then we must be
able to discuss the content of this sense-making, the world from the
system's perspective - the subjective world. The sense of subjectivity
we care about here is in the relationship between a system and the
world, consciousness not required. What matters are the dynamics between
an adaptive system and the environment, dynamics that can be described
for dogs, plants, and viruses. For humans this relationship is colored
in vivid conscious experience, and I started with this picture because
it is familiar, but we can just as well consider the structure of the
world from the perspective of a single cell or other basic forms of
life.

** 3. Umwelt
   :PROPERTIES:
   :ID:       82590109-fc22-4215-b807-6e82fb513cb9
   :CUSTOM_ID: f8968013-0b75-4f76-9706-5b9e2d7dd5fa
   :END:
All of this so far is concisely conveyed in Jakob von Uexküll's Umwelt
theory from his work in biology and semiotics in the early 20th century.
In brief, biosemiotics is the study of signs and meaning in biological
systems. An early pioneer in the field, von Uexküll was interested in
understanding meaning-making and how living systems interpret their
world so as to enable appropriate behavior. He advocated for conceiving
of living systems as subjects first and foremost, in contrast to
traditional reductive approaches in biology.

*** 3.1. the subjective perspective of living systems is crucial
    :PROPERTIES:
    :ID:       e5d1ed9c-c1a2-4bef-aa01-6c1ee4ca009e
    :CUSTOM_ID: 49276fa3-52d4-488b-ad83-0a9f266596f3
    :END:
To begin formalizing the study of animals' subjective worlds, von
Uexküll used the term umwelt ("environment") to describe the world as it
is interpreted by an organism. The umwelt is the perceived world /within
which a subject acts/. It encapsulates all the features of the external
world that carry significance to the organism given it's sense-making
resources and functional entanglement with the environment. The umwelt
is complemented by the umgebung which describes the full external
reality.

*** 3.2. environment as fundamental part of situated agents' intelligence
:PROPERTIES:
:ID:       2eeb586c-d803-4c46-8dff-071abeab61b0
:END:
In addition to championing the subjective nature of living systems, Umwelt theory also emphasizes the role of the environment in cognition.
If we do not appreciate the peculiar ways cognitive systems' relate to
their environments then we cannot understand the extent of their
abilities and intelligence. We shouldn't study fish out of water nor
birds in cages, these artificial environments being far removed from the
environmental niches in which they are built to act well in. The
environment is a crucial partner in the evolution of adaptive behavior.
Adaptive systems do not learn high fidelity representations of the world
for their own sake, but instead learn representations and habits that
guide effective behavior /in their local environments/. This recognition
of the importance of the environment sets the table nicely for further
exploration of distributed intelligence and theories that [[https://www.nyu.edu/gsas/dept/philo/courses/concepts/clark.html][extend cognition]] 
beyond the narrow confines of the skull.

*** 3.3. subjective and action-oriented sense-making
    :PROPERTIES:
    :ID:       b9e8f0be-d3f4-45d6-9117-7df8f0ef2cae
    :CUSTOM_ID: a9a326d8-90a1-49a5-9743-edd103ae0604
    :END:
What we get here is a framing of adaptive behavior that focuses on the
subjective sense-making of living systems and their distinctive
entanglements with the environment. These entanglements are feedback
loops relating meaningful features of the world to possible actions. The
umwelt isolates all the information a creature can interact with. It
describes a world model, and highlights the subjective and
action-oriented nature of biological intelligence. These are nice
footholds when considering how adaptive systems learn rich models of the
world.

** 4. Exploiting structure
   :PROPERTIES:
   :ID:       f230174c-1812-4bb3-b7d9-fc33ddbb9b4a
   :CUSTOM_ID: 6bfcc610-4007-4e8a-a94b-7b50e9ccface
   :END:
Let's bring this all back directly to the emergence of intelligence and
clarify what it means to exploit structure in the world. To first recap,
the connection to intelligence here is that evolution built world models
that are able to represent and exploit abstract domains of information
in the world. These world models are fundamentally situated in world,
engaging their environments with specific cognitive tools to exploit
particular patterns of information to enable adaptive behavior. Each
organisms' umwelt is structured by information evolution has identified
as useful to process and transform in guiding adaptive behavior. What an
organism can do with the information it has access to defines its
intelligence. What we want to understand is how adaptive systems learn
to make sense of, and exploit, different forms of structure in the
world.

*** 4.1. using world knowledge to do work
    :PROPERTIES:
    :ID:       52692514-0eb8-42b6-9853-cd59c3c38359
    :CUSTOM_ID: 37e86f18-c8af-4e6b-8fe4-98dfdc16d982
    :END:
But what does it actually mean to "exploit structure" as I've been
causally saying? The phrase is shorthand for "capture some information
about the world, process it, and take advantage of it in continued
engagement with the world". Exploiting structure entails using some
gained knowledge about the real world to achieve some end. I have
loosely used the phrase to describe individuals acting in the world as
well as learning that occurs across generations. For example, a simple
prokaryote exploits information about its surrounding chemical gradient
in navigating the world; in fact, the chemical gradient exhausts the
information about the world it is able to exploit. On the other end of
the spectrum are humans, whose evolutionary inheritance is a genetic
code within which evolution has compressed an immense amount of
information about the world into. The result of this genetic compression
of information about the world is that we are built to exploit tons of
structure in the world, have rich ways of understanding the world, and
are thus pretty intelligent systems.

*** 4.2. biology exploits physics and creates complexity
    :PROPERTIES:
    :ID:       7419c32c-7ef3-401e-ac97-807882db3512
    :CUSTOM_ID: 975876d0-98f0-4fc1-b452-60c9fd8e5b2f
    :END:
By exploiting the structure of physics, biology creates emergent levels
of structure and complexity. The dynamics governing mechanical physics
at the biological level allow for objects with particular shapes and
characteristics to capture, process, and integrate specific information
about the world. The building blocks of biological life are able to
store and direct energy using movement patterns that exploit the
dynamics of the mechanical force. The state of these objects relates to
the real world and this information can be used to do different types of
work. Shapes that persist through time and direct energy in useful ways
can evolve. As these basic self-organizing systems evolve, the range of
possible collective computations grows, allowing for more complex
organization and new functional engagements with the real world.

*** 4.3. adaptive transitions in information processing
    :PROPERTIES:
    :ID:       731057c2-d911-434d-b7f7-b2bb78fa555f
    :CUSTOM_ID: fdac96ee-90d8-4c99-a18d-59dd91a191eb
    :END:
In building world models to process and exploit structure in the world,
evolution discovered ways of capturing and using information about the
world that are particularly helpful for guiding adaptive behavior.
Chemical-sensing, epigenetics, nervous systems, linguistic
communication - these are all major transitions in information
processing that fueled adaptive success for their implementers by
broadening their horizons of perception and action. More complex world
models make use of information that was previously lost to noise to do
causal work on behalf of the subject perceiving the world. As evolution
naively explores possibilities affordances (ADD LINK BACK IN HERE) and
innovates in response to adaptive challenges, opportunities for
increased complexity and intelligence appear.

*** 4.4. adaptations exploit accessible structure
    :PROPERTIES:
    :ID:       714cbfd1-cc41-4a19-a21d-bd6768065e12
    :CUSTOM_ID: 8abffc00-e93e-4200-9c9d-e7dfc351c69e
    :END:
Keep in mind the subjective frame here as sense-making serves a
subjective perspective and all adaptations necessarily exploit some
/accessible/ structure in the world to enable productive behaviors. The
exploited structure could be at the level of fundamental physics,
chemical gradients, or social dynamics. The simplest illustration of
this is the above example of the emergent mechanics of basic biological
structures. Trivially, all living systems exploit the laws of physics to
maintain themselves. However, this framing is just as useful in
describing complex systems exploiting higher-level domains to accomplish
goals. Higher-level structure plays a similar role in framing an agent's
world as the mechanical force does for simple biological objects.
Although, the dynamics between physical systems and emergent
higher-levels of structure are more opaque. Next I'll introduce the
concept of affordances to help us better frame a cognitive systems
relation to the world.

** 5. Affordances
   :PROPERTIES:
    :ID:       180b7f3a-4a81-4b23-a5e3-bf166ad2b396
    :CUSTOM_ID: e8f844b8-6f88-429d-b01b-d80b62ab7b38
   :END:
We need more theoretical tools to help describe the relationship between
cognitive systems and the environment. The concept of affordances
developed by James Gibson in the third quarter of the 20th century is
one such tool. Gibson was an ecological psychologist studying visual
perception interested in how organisms see the world. He developed the
theory of affordances to expand the vocabulary we have for thinking
about perception, action, and the reciprocity between organisms and
their environments. In [[https://archive.org/details/pdfy-u5hmFOvOM2Civ4Gz/mode/2up][Gibson's own words]] "the affordances of the environment are
what it offers the animal, what it provides or furnishes, either for
good or ill". The upshot of affordances is the beginning of a theory of
the perception of meaning for living systems that emphasizes subjective
sense-making and action-oriented engagement with the world.

*** 5.1. perceiving possibilities
    :PROPERTIES:
    :ID:       fcaed959-4ed7-4adf-8db1-1a92bc5914f7
    :CUSTOM_ID: ada10dc0-0167-4532-b9db-d66a99311de0
    :END:
So what's an affordance? The term has been adopted and used by different
communities in varying ways, particularly in the field of human-computer
interfaces and in design generally. At their core, affordances are an
abstract category of behavioral opportunities defined by the
possibilities an environment offers to a particular agent. For most
humans a chair affords sitting, a pencil affords writing, and wood
affords fire building. For an ant these three affordances do not exist.
Affordances manifest at the intersection of a cognitive system's action
dispositions given its internal constitution and the reality of the
environment the system inhabits. Affordances describe a domain of
structure in the world from a subjective perspective, and really in a
sense capture /the/ structure of the world for a particular cognitive
system. To perceive an affordance is to perceive a possibility. There
are traces of von Uexküll's ideas here in the agent relative status of
affordances and the focus on action-oriented engagement with
environmental niches; the umwelt is colored by affordances.

*** 5.2. expanding the concept of affordances
    :PROPERTIES:
    :ID:       120263c2-d89a-4b93-8615-538c7821e9c4
    :CUSTOM_ID: a2a6b51a-f77e-4bd6-b1b3-93421722b480
    :END:
Perhaps in contrast to strict Gibsonians, I prefer a wider notion of
affordances that extends above and below the level of single organism of
cat or human for which we usually reserve the term perception. I find
the extended concept to be a useful companion in considering how
adaptive systems evolve in relation to the structure of the world
generally. From a system's subjective perspective the world always
offers a particular suite of possibilities, and this is as true for
simple biological objects as for an entire organism. Zooming out over
longer time scales we can consider evolutionary affordances, the
possible evolutionary paths, present for particular physical systems in
certain environmental niches.

*** 5.3. exploring evolutionary affordances
    :PROPERTIES:
    :ID:       4a73aabb-8d69-4990-9697-eee1a5e1e023
    :CUSTOM_ID: a9083dd2-5f95-4c5d-893d-ac7830de4580
    :END:
Because the set of all possible affordances for a system entirely
reflects how a system perceives and can interact with the world, the
solution space for an adaptive problem is necessarily a subset of a
system's set of possible affordances. Over time, adaptive systems learn
to exploit, by internalizing, the structure upon which evolutionarily
rewarding affordances rest - the result being a more adaptive set of
affordances. This internalization describes developments from the
physical organization cells and nervous systems take on, to the
emergence of social cooperation among humans. A clear example are the
visual priors that visual systems learn which mirror the statistics of
the surrounding visual world. This is why the many visual illusions we
see today are built with patterns and compositions that are rare, if at
all present, in the natural world. Adaptions reflect learned world
knowledge. As systems adapt and expand their world models to exploit
accessible domains of structure in the world such as chemical, visual,
or social information, they create new representations and affordances.
Evolution is an effective, although inefficient, search mechanism for
learning about the structure of the world.

*** 5.4. situated action-oriented agents
    :PROPERTIES:
    :ID:       18b2079d-5416-4195-bec2-0fde319eba8f
    :CUSTOM_ID: 7dc72e1a-58d1-43c7-92f5-a1022ab69c43
    :END:
If we return to the general notion of affordances as the possible
actions offered by the environment to an agent, we see that affordances
also clearly emphasize the situated nature of cognitive systems.
Affordance theory tells us we perceive things in relation to the
possibilities they present for action, which themselves describe the
coupled dynamics between an agent and the environment; natural
intelligence is fundamentally situated in the world. By giving us a way
to conceive of the subjective meaning of a signal to a cognitive system,
affordances are a powerful concept that is useful for a wide variety of
questions about cognition and intelligence.

** 6. Adaptive world models
   :PROPERTIES:
    :ID:       67de7625-cedb-4fc6-934c-08c9266b4ac8
    :CUSTOM_ID: aae54fe2-ab83-4659-92fa-9ea869b5c0e1
   :END:
Over time evolution learned about more and more structure in the world
as it naively explored affordances and the space of possible minds. This
discovered structure was built into the world models of increasingly
intelligent systems like ourselves, and manifests in our subjective
realities through phenomena like embodiment, memory, and our deep -
seemingly persistent - psychological sense of self. Our cognitive
architectures interpret the world in ways that produce the familiar
phenomenological tropes we have for understanding the world. Humans
possess wider means of understanding the world than other systems, our
subjective worlds are richer, and a great diversity of information in
the world carries meaning for us. Our cognitive flexibility and learning
ability creates open-ended affordances conditioned on different
experiential paths and cultural inheritances. However, this richness is
built atop representational scaffolding for making sense of the world
that we share in part with many other creatures.

*** 6.1. converging adaptive representational concepts
    :PROPERTIES:
    :ID:       30a14cf8-a456-41f1-9473-4b1c75dac15c
    :CUSTOM_ID: b721181f-9f97-4414-90ce-72a90a07a1cf
    :END:
The common representational concepts that define umwelt across the
biosphere are prominent because they pick out information about the
world that has proven effective for adaptive behavior. Over time these
useful ways of relating to the world were grooved into living systems.
Similar to how basic biological objects converge on certain shapes and
mechanics for doing work, cognitive systems on Earth converge on basic
representational constructs for understanding the world. Many of these
core representational concepts like embodiment, space, objects, and
intuitive physics frame our own subjective worlds and are so familiar
that they can be hard to appreciate as important components of
intelligence.

*** 6.2. life without objects?
    :PROPERTIES:
    :ID:       8640a366-cfa1-4eb8-9fd0-b1e9da322952
    :CUSTOM_ID: cff73187-aa6f-4aa9-8b93-c866974a87de
    :END:
For example, it is hard to imagine living without an intuitive concept
for something like the general category of object, a subjective world
where things like rocks and fire sit idle outside one's cognitive loops,
registering zero affordances. Instead, we are equipped to flexibly
integrate new information and emergent possibilities. When I encounter
new objects I already know a lot of information about them given the web
of world knowledge I already have. For example: I know they will fall
when dropped unless specifically designed otherwise, that sharp objects
may cut me, and that heavy objects are hard to move. These basic
intuitions betray a vast amount of world knowledge that is constantly
helping me navigate the world. Again, I recommend reading accounts from
abnormal psychology to develop an appreciation for the fragility of our
own familiar percepts and phenomenology.

*** 6.3. representational scaffolding
    :PROPERTIES:
    :ID:       ca9311a8-4c4a-44af-97a0-cd394a861239
    :CUSTOM_ID: 2995116a-aa64-4966-9397-a1de38dad051
    :END:
We have been tuned to the world we live in by evolution. Our subjective
worlds are filled with structure and affordances that support our
behavior and the preservation of our informational integrity. The rich
representational scaffolding we have for making sense of the world forms
the stage upon which new and higher-level entities gain meaning. We
seamlessly find meaning in language, art, religion, social
relationships, mathematics, and culture generally because of the rich
forms of sense-making we inherited from evolution. Human intelligence is
so far unique on Earth, but the dynamics responsible for our
intelligence and meaning-making extend throughout all of evolution. In
trying to understand the development of the basic representational
concepts underlying our own general intelligence we should keep in mind
the subjective and action-oriented framework within which these
competencies emerged.

** 7. Wrapping up
   :PROPERTIES:
    :ID:       8df341d1-9d7d-4a45-b0c8-80fb0d0233ff
    :CUSTOM_ID: b4511a0b-1a9a-49a7-87f0-ab9068225788
   :END:
Intelligence is a hard problem. I think the more tools we have for
trying to understand how adaptive systems learn about the structure of
the world the more successful our inquiries into the emergence of
intelligence will be. I've tried here to relate the usefulness of
considering adaptive systems as fundamentally situated in the world and
of intelligence as the product of subjective sense-making. I introduced
the concepts of umwelt and affordances to help frame the discussion
about how living systems relate to the world and adapt to exploit the
structure of their niches. There are many loose ends here related to the
mechanisms of evolution, life, learning, representation, agency,
artificial intelligence and much more. I hope to continue exploring some
of these in the future!
